In [ ]:
# Name:Salve Sumit Sunil
# Roll no:119
# Batch:T3
# Assignmnet Title:  INTRODUCTION TO DATA SCIENCE
'''
Defining data science and big data, Recognizing the different types of
data, Gaining insight into the data science process, Data Science Process:
Overview, Different steps, Machine Learning Definition and Relation
with Data Science
'''
# Date: 01/08/2025

In [8]:
import numpy as np

In [9]:

#Creating a numpy array1
arr1 = np.array([1,2,3,4])
arr1


array([1, 2, 3, 4])

In [10]:
##Creating a numpy array2
arr2 = np.array([[3, 4, 9],[1,5,3]])
arr2

array([[3, 4, 9],
       [1, 5, 3]])

In [11]:
#Data types of arrays
arr2 = np.array([[3.8, 4, 9],[1,5,3]])
arr2.dtype

dtype('float64')

In [12]:
arr2.size

6

In [ ]:
arr2.ndim

2

In [5]:
arr2.shape

(2, 3)

In [23]:
arr2.itemsize

8

In [24]:
arr2[0, 1]

np.int64(4)

In [ ]:
#reshape() – Changes shape of array:
arr1.reshape(2, 2)


array([[1, 2],
       [3, 4]])

In [ ]:
#np.arange() – Creates a range of values:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Addiing two arrays
arr2 = np.array([[3, 4, 9],[1,5,3]])
arr3 = np.array([[2,64.5, 4],[13,63,4]])
S = arr2 + arr3
S

array([[ 5. , 68.5, 13. ],
       [14. , 68. ,  7. ]])

In [ ]:
#Sub two arrays
arr2 = np.array([[3, 4, 9],[1,5,3]])
arr3 = np.array([[2,64.5, 4],[13,63,4]])
S = arr2 - arr3
S

In [18]:
#Multiplying two arrays
arr2 = np.array([[3, 4, 9],[1,5,3]])
arr3 = np.array([[2,64.5, 4],[13,63,4]])
S = arr2 * arr3
S

array([[  6., 258.,  36.],
       [ 13., 315.,  12.]])

In [ ]:
#argmac() – Index of max value
arr2.argmax()

np.int64(2)

In [ ]:
#argmin() – Index of min value
arr2.argmin()

np.int64(3)